202411032257

diff --git a/roll b/roll
--- a/roll
+++ b/roll
@@ -35,18 +35,20 @@ function x-stump {
     }
 }
 
-function d-lang {
+function detect-lang {
     wifi-connected-p
     [[ "$wc_p" -eq 1 ]] && return 1
+    test_stump="$(echo "$1" | tr -d '[a-zA-Z[:punct:][:digit:]]')"
+    [[ -z "$test_stump" ]] && return 1
     if ! cmp -s <(echo "$1") <(echo "$1" | iconv -c -f utf8 -t ascii//TRANSLIT)
     then
 	if echo "$1" | grep -qP '\P{ASCII}'
 	   # \P in pcresyntax(3) manual
 	   # https://perldoc.perl.org/perlrecharclass#Unicode-Properties
 	then
-	    return 0
+	    return 0 # yes translate
 	else
-	    return 1
+	    return 1 # no translate
        fi
     else
 	return 1
@@ -64,7 +66,7 @@ function prepare {
     x-url "$original"
     x-ext "$original"
     x-stump "$original"
-    d-lang "$v_stump" && {
+    detect-lang "$v_stump" && {
 	echolor blue-aquamarine ":: Translating ““$v_stump””"
 	v_stump="$(trans -identify -b -e google "$v_stump") "
 	echolor blue-orange ":: To ““$v_stump””\n:: Alternative? > " 1
@@ -92,9 +94,13 @@ function prepare {
 	echolor red ":: Not done; clobber"
 	return 1
     }
-    echo -ne "\033[38;5;208m:: "
-    mv -vn "$original_full" "$original_dir/$final" && echo "$original_full --> $original_dir/$final" >> "$log"
-    echo -ne "\033[0m"
+    mv -n "$original_full" "$original_dir/$final" && {
+	echo "$original_full --> $original_dir/$final" >> "$log"
+	echolor orange ":: Moved."
+    } || {
+	echo "FAILURE:::: $original_full --> $original_dir/$final" >> "$log"
+	echolor red ":: Failed to move!"
+    }
 }
 
 echolor blue-orange ":: Rolling ““${#@}”” files"
